const JOBS_DATA = [
    {
        id: 1,
        title: "SDE Intern",
        company: "Razorpay",
        location: "Bangalore",
        mode: "Remote",
        experience: "Fresher",
        skills: ["React", "Node.js", "Javascript"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹25k–₹40k/month Internship",
        applyUrl: "https://razorpay.com/jobs/sde-intern",
        description: "Join the core payments team to build scalable frontend components. You will collaborate with senior engineers to deliver high-impact features."
    },
    {
        id: 2,
        title: "Graduate Engineer Trainee",
        company: "TCS",
        location: "Pune",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "SQL", "Spring Boot"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "3–5 LPA",
        applyUrl: "https://www.tcs.com/careers/get-2024",
        description: "Entry-level role for engineering graduates. Participate in comprehensive training on enterprise technologies and work on global projects."
    },
    {
        id: 3,
        title: "Junior Backend Developer",
        company: "Swiggy",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Go", "Microservices", "Redis"],
        source: "Indeed",
        postedDaysAgo: 0,
        salaryRange: "10–18 LPA",
        applyUrl: "https://careers.swiggy.com/jobs/backend-jr",
        description: "Develop high-performance microservices for order management. Focus on low-latency systems and large-scale data processing."
    },
    {
        id: 4,
        title: "Frontend Intern",
        company: "Zomato",
        location: "Gurgaon",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["React", "CSS", "TypeScript"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "₹20k–₹35k/month Internship",
        applyUrl: "https://zomato.com/careers/frontend-intern",
        description: "Work on user-facing features for the food delivery app. Optimize web performance and ensure a seamless UI/UX across devices."
    },
    {
        id: 5,
        title: "QA Intern",
        company: "PhonePe",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Selenium", "Java", "Testing"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        salaryRange: "₹30k/month Internship",
        applyUrl: "https://www.phonepe.com/careers/qa-intern",
        description: "Assist the QA team in manual and automated testing. Design test cases for new payment features and report critical bugs."
    },
    {
        id: 6,
        title: "Data Analyst Intern",
        company: "Flipkart",
        location: "Bangalore",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Python", "SQL", "Tableau"],
        source: "Naukri",
        postedDaysAgo: 1,
        salaryRange: "₹25k/month Internship",
        applyUrl: "https://www.flipkart.com/careers/data-intern",
        description: "Analyze customer behavior data to improve conversion rates. Build dashboards and present insights to the product marketing team."
    },
    {
        id: 7,
        title: "Java Developer",
        company: "Infosys",
        location: "Mysore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Java", "Spring", "Hibernate"],
        source: "Naukri",
        postedDaysAgo: 7,
        salaryRange: "4–6 LPA",
        applyUrl: "https://www.infosys.com/careers/",
        description: "Develop enterprise-grade applications for global clients. Collaborate in an Agile environment and follow clean code practices."
    },
    {
        id: 8,
        title: "Python Developer",
        company: "Cred",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Python", "Django", "PostgreSQL"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "12–20 LPA",
        applyUrl: "https://cred.club/careers/python-dev",
        description: "Build robust APIs for credit card management. Focus on security, reliability, and high-performance backend systems."
    },
    {
        id: 9,
        title: "React Developer",
        company: "Razorpay",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["React", "Redux", "SCSS"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "15–25 LPA",
        applyUrl: "https://razorpay.com/jobs/react-dev",
        description: "Maintain and enhance the payment gateway dashboard. Collaborate with designers to translate pixel-perfect mocks into code."
    },
    {
        id: 10,
        title: "Software Engineer",
        company: "Paytm",
        location: "Noida",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Java", "Spring Boot", "Kafka"],
        source: "Indeed",
        postedDaysAgo: 4,
        salaryRange: "8–12 LPA",
        applyUrl: "https://paytm.com/careers/sde",
        description: "Core banking team role focusing on transaction reliability. Implement microservices and monitor production systems."
    },
    {
        id: 11,
        title: "Full Stack Developer",
        company: "Zoho",
        location: "Chennai",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Java", "JS", "Postgres"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "6–12 LPA",
        applyUrl: "https://www.zoho.com/careers/full-stack",
        description: "Help build Zoho's enterprise SaaS suite. Full ownership of features from UI to database design and optimization."
    },
    {
        id: 12,
        title: "Cloud Support Engineer",
        company: "Amazon",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["AWS", "Linux", "Networking"],
        source: "LinkedIn",
        postedDaysAgo: 6,
        salaryRange: "10–14 LPA",
        applyUrl: "https://www.amazon.jobs/cloud-support",
        description: "Troubleshoot complex AWS infrastructure issues for enterprise customers. Focus on network diagnostics and cloud security."
    },
    {
        id: 13,
        title: "Android Intern",
        company: "Swiggy",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Kotlin", "Android Studio", "MVVM"],
        source: "Indeed",
        postedDaysAgo: 2,
        salaryRange: "₹35k/month Internship",
        applyUrl: "https://careers.swiggy.com/jobs/android-intern",
        description: "Develop new features for the Swiggy Android application. Learn industry-level mobile development workflows and testing."
    },
    {
        id: 14,
        title: "Business Analyst",
        company: "Accenture",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Excel", "Tableau", "SQL"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "5–8 LPA",
        applyUrl: "https://www.accenture.com/careers",
        description: "Liaise between technical teams and business stakeholders. Document requirements and perform data-driven analysis for client strategy."
    },
    {
        id: 15,
        title: "Full Stack Intern",
        company: "Freshworks",
        location: "Chennai",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Ruby on Rails", "React", "Ember.js"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹30k/month Internship",
        applyUrl: "https://www.freshworks.com/careers/intern",
        description: "Join our global SaaS development team. Work on customer support software modules and improve platform stability."
    },
    {
        id: 16,
        title: "DevOps Engineer",
        company: "Cisco",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Docker", "Kubernetes", "Azure"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "14–22 LPA",
        applyUrl: "https://jobs.cisco.com/",
        description: "Build CI/CD pipelines for cloud-native applications. Automate infrastructure and ensure high availability for global services."
    },
    {
        id: 17,
        title: "Node.js Developer",
        company: "Juspay",
        location: "Bangalore",
        mode: "Remote",
        experience: "3-5",
        skills: ["Node.js", "Redis", "Elasticsearch"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "20–35 LPA",
        applyUrl: "https://juspay.in/careers",
        description: "Design high-throughput payment systems. Optimize Node.js event-loop performance and lead technical architecture decisions."
    },
    {
        id: 18,
        title: "System Engineer",
        company: "Cognizant",
        location: "Kochi",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "Mainframe", "C#"],
        source: "Naukri",
        postedDaysAgo: 8,
        salaryRange: "4–5 LPA",
        applyUrl: "https://careers.cognizant.com/",
        description: "Support large-scale banking systems. Perform system maintenance, patch management, and resolve production support tickets."
    },
    {
        id: 19,
        title: "UI Designer Intern",
        company: "Dream11",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Figma", "Sketch", "Prototyping"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹25k/month Internship",
        applyUrl: "https://about.dream11.com/careers",
        description: "Create visual designs for fantasy sports features. Work with product managers to iterate on high-fidelity designs and user flows."
    },
    {
        id: 20,
        title: "Security Analyst",
        company: "IBM",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Cybersecurity", "SIEM", "Python"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        salaryRange: "10–16 LPA",
        applyUrl: "https://www.ibm.com/careers/",
        description: "Monitor and respond to security threats within global network infrastructure. Perform vulnerability assessments and security audits."
    },
    {
        id: 21,
        title: "Machine Learning Intern",
        company: "Ola Electric",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Python", "PyTorch", "OpenCV"],
        source: "Indeed",
        postedDaysAgo: 2,
        salaryRange: "₹40k/month Internship",
        applyUrl: "https://olaelectric.com/careers",
        description: "Research computer vision algorithms for autonomous driving. Evaluate model performance and optimize for edge devices."
    },
    {
        id: 22,
        title: "Data Engineer",
        company: "Oyo",
        location: "Gurgaon",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Spark", "Airflow", "SQL"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "14–22 LPA",
        applyUrl: "https://www.oyorooms.com/careers",
        description: "Build robust data pipelines for analytics. Focus on data warehouse performance and automate ETL processes across cloud platforms."
    },
    {
        id: 23,
        title: "Associate Software Engineer",
        company: "Capgemini",
        location: "Pune",
        mode: "Remote",
        experience: "0-1",
        skills: ["Java", "Angular", "Typescript"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "4–7 LPA",
        applyUrl: "https://www.capgemini.com/careers/",
        description: "Deliver digital transformation projects for Fortune 500 clients. Learn microservice orchestration and cloud development patterns."
    },
    {
        id: 24,
        title: "Golang Developer",
        company: "Groww",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["Go", "Kafka", "PostgreSQL"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "18–30 LPA",
        applyUrl: "https://groww.in/careers",
        description: "Build scalable fintech backend services. Focus on low-latency trading infrastructure and real-time data processing systems."
    },
    {
        id: 25,
        title: "Web Developer Intern",
        company: "Meesho",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["HTML", "CSS", "Next.js"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹20k/month Internship",
        applyUrl: "https://meesho.io/careers",
        description: "Help build and optimize social commerce features. Work closely with frontend engineers to improve mobile web experiences."
    },
    {
        id: 26,
        title: "Backend Engineer",
        company: "Postman",
        location: "Bangalore",
        mode: "Remote",
        experience: "3-5",
        skills: ["Node.js", "AWS", "DynamoDB"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "25–45 LPA",
        applyUrl: "https://www.postman.com/careers",
        description: "Develop the core infrastructure for the world's leading API platform. High-ownership role focusing on scalability and reliability."
    },
    {
        id: 27,
        title: "iOS Developer",
        company: "Urban Company",
        location: "Gurgaon",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Swift", "SwiftUI", "Combine"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "15–28 LPA",
        applyUrl: "https://www.urbancompany.com/careers",
        description: "Build high-quality mobile experiences for our home services platform. Ensure feature parity and performance across iOS devices."
    },
    {
        id: 28,
        title: "Site Reliability Engineer",
        company: "InMobi",
        location: "Bangalore",
        mode: "Onsite",
        experience: "3-5",
        skills: ["Python", "Terraform", "Jenkins"],
        source: "Indeed",
        postedDaysAgo: 5,
        salaryRange: "22–35 LPA",
        applyUrl: "https://www.inmobi.com/careers",
        description: "Maintain the availability and reliability of large-scale ad platforms. Focus on automation, observability, and incident management."
    },
    {
        id: 29,
        title: "Research Intern",
        company: "Microsoft",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["C++", "Python", "Algorithms"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹50k/month Internship",
        applyUrl: "https://careers.microsoft.com/",
        description: "Participate in cutting-edge computer science research projects. Collaborate with world-renowned researchers and write high-quality code."
    },
    {
        id: 30,
        title: "Full Stack Engineer",
        company: "Shiprocket",
        location: "Delhi",
        mode: "Remote",
        experience: "3-5",
        skills: ["PHP", "Laravel", "React"],
        source: "Naukri",
        postedDaysAgo: 7,
        salaryRange: "12–20 LPA",
        applyUrl: "https://www.shiprocket.in/careers",
        description: "Develop merchant dashboard and core eCommerce shipping features. Improve platform efficiency and build new integration modules."
    },
    {
        id: 31,
        title: "React Native Developer",
        company: "CoinSwitch",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["React Native", "Javascript", "iOS/Android"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "15–25 LPA",
        applyUrl: "https://coinswitch.co/careers",
        description: "Maintain crypto exchange mobile application. Focus on smooth UI transitions, secure wallet management, and live trading features."
    },
    {
        id: 32,
        title: "Graduate Analyst",
        company: "Deloitte",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Excel", "SQL", "PowerBI"],
        source: "Indeed",
        postedDaysAgo: 9,
        salaryRange: "6–9 LPA",
        applyUrl: "https://www2.deloitte.com/careers/",
        description: "Support client diagnostic and implementation projects. Analyze financials, business processes, and perform strategic reviews."
    },
    {
        id: 33,
        title: "Software Engineer",
        company: "Oracle",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Java", "PL/SQL", "Oracle DB"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "12–18 LPA",
        applyUrl: "https://www.oracle.com/careers/",
        description: "Work on mission-critical database and cloud applications. Develop back-end business logic and optimize database queries."
    },
    {
        id: 34,
        title: "Intern",
        company: "SAP Labs",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "ABAP", "Cloud"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "₹30k/month Internship",
        applyUrl: "https://www.sap.com/careers/",
        description: "Contribute to enterprise resource planning software. Work on SAP's cloud platform and gain exposure to industrial software engineering."
    },
    {
        id: 35,
        title: "Frontend Developer",
        company: "Byju's",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Vue.js", "Javascript", "SCSS"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        salaryRange: "10–18 LPA",
        applyUrl: "https://byjus.com/careers/",
        description: "Enhance the student learning interface. Optimize web visuals, handle real-time video player features, and fix UI bugs."
    },
    {
        id: 36,
        title: "Junior Data Scientist",
        company: "UpGrad",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Python", "Sklearn", "Stats"],
        source: "Naukri",
        postedDaysAgo: 2,
        salaryRange: "8–13 LPA",
        applyUrl: "https://www.upgrad.com/careers/",
        description: "Build predictive models for learner retention. Collaborate with the data team on EDA, modeling, and dashboard creation."
    },
    {
        id: 37,
        title: "Developer Associate",
        company: "Dell Technologies",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Python", "Linux", "Scripting"],
        source: "LinkedIn",
        postedDaysAgo: 6,
        salaryRange: "8–11 LPA",
        applyUrl: "https://jobs.dell.com/",
        description: "Work on internal automation and infrastructure monitoring tools. Support global storage and cloud computing services."
    },
    {
        id: 38,
        title: "Software Developer",
        company: "ZOHO",
        location: "Tenkasi",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["C", "C++", "Java"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "4–8 LPA",
        applyUrl: "https://www.zoho.com/careers/",
        description: "Solve complex engineering problems for enterprise software. Focus on high-performance algorithms and system design."
    },
    {
        id: 39,
        title: "Associate Product Manager",
        company: "Unacademy",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Analytics", "Product Design", "SQL"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "12–18 LPA",
        applyUrl: "https://unacademy.com/careers/",
        description: "Assist in product lifecycle management. Conduct market research, user interviews, and define feature requirements for the dev team."
    },
    {
        id: 40,
        title: "Backend Intern",
        company: "Smallcase",
        location: "Bangalore",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Node.js", "MongoDB", "Express"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "₹25k/month Internship",
        applyUrl: "https://www.smallcase.com/careers",
        description: "Integrate brokers and build financial data APIs. Learn backend engineering principles in a high-growth fintech startup."
    },
    {
        id: 41,
        title: "Data Analyst",
        company: "HCLTech",
        location: "Noida",
        mode: "Onsite",
        experience: "1-3",
        skills: ["SQL", "Python", "Tableau"],
        source: "Indeed",
        postedDaysAgo: 7,
        salaryRange: "5–9 LPA",
        applyUrl: "https://www.hcltech.com/careers",
        description: "Generate reporting and dashboards for global clients. Interpret data and derive actionable business insights for IT strategy."
    },
    {
        id: 42,
        title: "React Developer",
        company: "Lenskart",
        location: "Gurgaon",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["React", "CSS-in-JS", "Next.js"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "12–20 LPA",
        applyUrl: "https://lenskart.com/careers",
        description: "Build premium eyewear shopping experiences. Focus on web performance, mobile responsiveness, and 3D virtual try-on features."
    },
    {
        id: 43,
        title: "QA Engineer",
        company: "Wipro",
        location: "Pune",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Selenium", "Cucumber", "API Testing"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "5–8 LPA",
        applyUrl: "https://careers.wipro.com/",
        description: "Plan and execute automated tests for enterprise portals. Monitor quality throughout the development lifecycle and report regressions."
    },
    {
        id: 44,
        title: "SDE 1",
        company: "Cars24",
        location: "Gurgaon",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Java", "Spring Boot", "MySQL"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "14–22 LPA",
        applyUrl: "https://www.cars24.com/careers",
        description: "Maintain core car valuation and inventory systems. Optimize backend APIs and collaborate with cross-functional product teams."
    },
    {
        id: 45,
        title: "Flutter Developer",
        company: "Nykaa",
        location: "Mumbai",
        mode: "Remote",
        experience: "1-3",
        skills: ["Flutter", "Dart", "Firebase"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "10–18 LPA",
        applyUrl: "https://nykaa.com/careers/",
        description: "Build new modules for our multi-platform retail mobile application. Ensure smooth animations and high-performance beauty shopping UX."
    },
    {
        id: 46,
        title: "Research Scientist",
        company: "Google",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Python", "TensorFlow", "Math"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "25–40 LPA",
        applyUrl: "https://careers.google.com/",
        description: "Participate in AI research focused on multilingual language models. Evaluate theoretical approaches and contribute to experimental code."
    },
    {
        id: 47,
        title: "Cloud Architect",
        company: "Vymo",
        location: "Bangalore",
        mode: "Remote",
        experience: "3-5",
        skills: ["Kubernetes", "Azure", "Python"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "25–40 LPA",
        applyUrl: "https://getvymo.com/careers",
        description: "Design fault-tolerant cloud architecture for enterprise sales CRM. Manage large scale migrations and optimize cloud compute costs."
    },
    {
        id: 48,
        title: "Salesforce Admin",
        company: "Cognizant",
        location: "Chennai",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Salesforce", "CRM", "Apex"],
        source: "Naukri",
        postedDaysAgo: 8,
        salaryRange: "6–10 LPA",
        applyUrl: "https://careers.cognizant.com/",
        description: "Support CRM operations for Fortune 500 companies. Maintain user permissions, design reports, and automate business workflows."
    },
    {
        id: 49,
        title: "Blockchain Intern",
        company: "Polygon",
        location: "Remote",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Solidity", "Rust", "Ethereum"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹45k/month Internship",
        applyUrl: "https://polygon.technology/careers",
        description: "Contribute to core protocol and SDK development. Learn smart-contract security and gain exposure to decentralized infrastructure."
    },
    {
        id: 50,
        title: "Technical Lead",
        company: "Clear",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "3-5",
        skills: ["Java", "Spring Boot", "Leadership"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "35–55 LPA",
        applyUrl: "https://clear.in/careers",
        description: "Lead dev teams task with fintech scaling. Drive system architectural decisions and mentor junior engineers while writing core libs."
    },
    {
        id: 51,
        title: "Django Developer",
        company: "Licious",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "3-5",
        skills: ["Python", "Django", "Postgres"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "18–28 LPA",
        applyUrl: "https://www.licious.in/careers",
        description: "Core e-commerce backend team. Optimize supply chain management APIs and handle traffic surges during sales events."
    },
    {
        id: 52,
        title: "Data Analyst Trainee",
        company: "Genpact",
        location: "Gurgaon",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["VBA", "PowerBI", "Access"],
        source: "Indeed",
        postedDaysAgo: 6,
        salaryRange: "4–6 LPA",
        applyUrl: "https://www.genpact.com/careers",
        description: "Collect and prepare operational data for analytics. Maintain automation scripts and ensure high data integrity for client reports."
    },
    {
        id: 53,
        title: "Senior QA Engineer",
        company: "Palo Alto Networks",
        location: "Bangalore",
        mode: "Onsite",
        experience: "3-5",
        skills: ["Networking", "Python", "Automation"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "25–40 LPA",
        applyUrl: "https://jobs.paloaltonetworks.com/",
        description: "Verify next-gen firewall security features. Design complex network testbeds and automate security protocols validation."
    },
    {
        id: 54,
        title: "App Developer Intern",
        company: "Dunzo",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["React Native", "Firebase", "Redux"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "₹18k/month Internship",
        applyUrl: "https://www.dunzo.com/careers",
        description: "Contribute to the last-mile delivery application. Enhance order updates UI and work on logistics-specific mobile features."
    },
    {
        id: 55,
        title: "Infra Engineer",
        company: "BrowserStack",
        location: "Mumbai",
        mode: "Remote",
        experience: "1-3",
        skills: ["AWS", "Docker", "Go"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "15–25 LPA",
        applyUrl: "https://www.browserstack.com/careers",
        description: "Help automate thousands of real mobile and browser VMs. Ensure high network reliable and low-latency testing envs."
    },
    {
        id: 56,
        title: "Product Analyst",
        company: "Acko",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Mixpanel", "SQL", "Excel"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "10–15 LPA",
        applyUrl: "https://www.acko.com/careers",
        description: "Monitor insurance purchase funnel metrics. Identify bottlenecks and suggest a/b tests to product managers based on user data."
    },
    {
        id: 57,
        title: "Backend Engineer",
        company: "Spinny",
        location: "Gurgaon",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Go", "MySQL", "AWS"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "14–24 LPA",
        applyUrl: "https://www.spinny.com/careers",
        description: "Improve car inspection tracking and management APIs. Optimize database schemas for high-growth operational scale."
    },
    {
        id: 58,
        title: "MERN Stack Intern",
        company: "Jupiter",
        location: "Bangalore",
        mode: "Remote",
        experience: "Fresher",
        skills: ["MongoDB", "Express", "React", "Node"],
        source: "Indeed",
        postedDaysAgo: 0,
        salaryRange: "₹25k/month Internship",
        applyUrl: "https://jupiter.money/careers",
        description: "Work with our cards team on banking UI features. Develop performant Node.js services and build responsive dashboards."
    },
    {
        id: 59,
        title: "Embedded Systems Intern",
        company: "Ather Energy",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["C", "RTOS", "Electronics"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹30k/month Internship",
        applyUrl: "https://www.atherenergy.com/careers",
        description: "Assist in developing firmware for electric scooter dashboards. Test peripheral communication and focus on system performance."
    },
    {
        id: 60,
        title: "DevOps Engineer",
        company: "Zomato",
        location: "Gurgaon",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Terraform", "AWS", "Prometheus"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "18–28 LPA",
        applyUrl: "https://www.zomato.com/careers",
        description: "Manage large scale AWS clusters for high-traffic food delivery volumes. Instrument dashboard and observability for microservices."
    }
];

if (typeof module !== 'undefined' && module.exports) {
    module.exports = JOBS_DATA;
}
